<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SRILAKSHMANAR" failures="0" tests="6" name="drighna.ogj.Communicate" time="0.014" errors="1" timestamp="2025-02-11T18:56:10 IST" skipped="5">
  <testcase classname="drighna.ogj.Communicate" name="login_credentials" time="0.000">
    <skipped/>
  </testcase> <!-- login_credentials -->
  <system-out/>
  <testcase classname="drighna.ogj.Communicate" name="setUp" time="0.014">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
at java.base/java.util.Properties.put(Properties.java:1346)
at java.base/java.util.Properties.setProperty(Properties.java:230)
at java.base/java.lang.System.setProperty(System.java:1051)
at drighna.ogj.BaseClass.setUp(BaseClass.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase classname="drighna.ogj.Communicate" name="sms_temp" time="0.000">
    <skipped/>
  </testcase> <!-- sms_temp -->
  <system-out/>
  <testcase classname="drighna.ogj.Communicate" name="sendsms" time="0.000">
    <skipped/>
  </testcase> <!-- sendsms -->
  <system-out/>
  <testcase classname="drighna.ogj.Communicate" name="sendemail" time="0.000">
    <skipped/>
  </testcase> <!-- sendemail -->
  <system-out/>
  <testcase classname="drighna.ogj.Communicate" name="noticeboard" time="0.000">
    <skipped/>
  </testcase> <!-- noticeboard -->
  <system-out/>
</testsuite> <!-- drighna.ogj.Communicate -->
